version: '3.1'

services:
  caddy:
    container_name: caddy
    image: stefanprodan/caddy
    container_name: caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9080:9080"
    volumes:
      - ./caddy/:/etc/caddy/
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  db:
    container_name: db
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD="
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_ROOT_HOST=%"
    expose:
      - 3306
    restart: unless-stopped

  heplify-server:
    image: sipcapture/heplify-server:latest
    container_name: heplify-server
    ports:
      - "9060:9060"
      - "9060:9060/udp"
    command:
      - './heplify-server'
    environment:
      - "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_DBDRIVER=mysql"
      - "HEPLIFYSERVER_DBADDR=db:3306"
      - "HEPLIFYSERVER_DBUSER=root"
      - "HEPLIFYSERVER_DBPASS="
      - "HEPLIFYSERVER_LOGLVL=info"
      - "HEPLIFYSERVER_LOGSTD=true"
      - "HEPLIFYSERVER_PROMADDR=0.0.0.0:9096"
      - "HEPLIFYSERVER_PROMTARGETIP="
      - "HEPLIFYSERVER_PROMTARGETNAME="
      - "HEPLIFYSERVER_DBDROPDAYS=7"
#      - "HEPLIFYSERVER_ESADDR=http://elasticsearch:9200"
    restart: unless-stopped
    expose:
      - 9096
    depends_on:
      - db
    labels:
      org.label-schema.group: "monitoring"

  homer-webapp:
    container_name: homer-webapp
    image: sipcapture/homer-webapp
    environment:
      - "DB_HOST=db"
      - "DB_USER=root"
      - "DB_PASS="
    expose:
      - 80
    volumes:
      - ./docker-compose.yml:/homer-semaphore/.bootstrapped
    restart: unless-stopped
    depends_on:
      - db
version: '3.1'

services:
  caddy:
    container_name: caddy
    image: stefanprodan/caddy
    container_name: caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
      - "9080:9080"
    volumes:
      - ./caddy/:/etc/caddy/
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  db:
    container_name: db
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD="
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_ROOT_HOST=%"
    expose:
      - 3306
    restart: unless-stopped

  heplify-server:
    image: sipcapture/heplify-server:latest
    container_name: heplify-server
    ports:
      - "9060:9060"
      - "9060:9060/udp"
    command:
      - './heplify-server'
    environment:
      - "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_DBDRIVER=mysql"
      - "HEPLIFYSERVER_DBADDR=db:3306"
      - "HEPLIFYSERVER_DBUSER=root"
      - "HEPLIFYSERVER_DBPASS="
      - "HEPLIFYSERVER_LOGLVL=info"
      - "HEPLIFYSERVER_LOGSTD=true"
      - "HEPLIFYSERVER_PROMADDR=0.0.0.0:9096"
      - "HEPLIFYSERVER_PROMTARGETIP="
      - "HEPLIFYSERVER_PROMTARGETNAME="
      - "HEPLIFYSERVER_DBDROPDAYS=7"
    restart: unless-stopped
    expose:
      - 9096
    depends_on:
      - db
    labels:
      org.label-schema.group: "monitoring"

  homer-webapp:
    container_name: homer-webapp
    image: sipcapture/homer-webapp
    environment:
      - "DB_HOST=db"
      - "DB_USER=root"
      - "DB_PASS="
    expose:
      - 80
    volumes:
      - ./docker-compose.yml:/homer-semaphore/.bootstrapped
    restart: unless-stopped
    depends_on:
      - db

  telegraf:
    image: telegraf:1.5-alpine
    restart: unless-stopped
    volumes:
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - "8092:8092/udp"
      - "8125:8125/udp"
    depends_on:
      - heplify-server
